apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sre-tenant-operator-config
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: 03-sre/tenant-operator-config
    repoURL: 'https://github.com/stakater/gitops-config-template.git'
    targetRevision: main
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
