apiVersion: tenantoperator.stakater.com/v1beta1
kind: Tenant
metadata:
  name: veeru
spec:
  owners:
   users:
   - hanzala@stakater.com
  quota: medium
  argocd:
    sourceRepos:
      - 'https://github.com/stakater/gitops-config-template'
      - 'https://nexus-helm-stakater-nexus.apps.binero-test.8sdzwd1l.kubeapp.cloud/repository/helm-charts/'
  templateInstances:
  - spec:
      template: tenant-vault-access
      sync: true
  namespaces:
  - stage
  - prod
