apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gabbar-stakater-nordmart-review-dev
  namespace: openshift-gitops
  labels:
    stakater.com/tenant: gabbar
    stakater.com/env: dev
    stakater.com/kind: dev
spec:
  destination:
    namespace: gabbar-dev
    server: 'https://kubernetes.default.svc'
  project: gabbar
  source:
    path: 01-gabbar/01-stakater-nordmart-review/01-dev
    repoURL: 'https://github.com/stakater/gitops-config-template.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
